export const roles = [
  "user",
  "admin",
  "production",
  "procurement",
  "sales",
  "finance",
];

const CRUD = ["create", "read", "update", "delete"];
export const ROLE_PERMISSIONS = {
  admin: {
    products: CRUD,
    boms: CRUD,
    inventories: CRUD,
    purchaseorders: CRUD,
    salesorders: CRUD,
    rawmaterials: CRUD,
    finances: CRUD,
    users: CRUD,
    notifications: CRUD,
  },
  user: {
    products: ["read"],
    boms: [],
    inventories: [],
    purchaseorders: [],
    salesorders: [],
    rawmaterials: [],
    finances: [],
    users: [],
    notifications: ["read"],
  },
  production: {
    products: ["read"],
    boms: CRUD,
    inventories: ["read", "update"],
    purchaseorders: ["read"],
    salesorders: ["read"],
    rawmaterials: ["read"],
    finances: [],
    users: ["read"],
    notifications: ["read", "create"],
  },
  procurement: {
    products: ["read"],
    boms: ["read"],
    inventories: ["read"],
    purchaseorders: CRUD,
    salesorders: ["read"],
    rawmaterials: CRUD,
    finances: ["read"],
    users: ["read"],
    notifications: ["read", "create"],
  },
  sales: {
    products: ["read", "update"],
    boms: ["read"],
    inventories: ["read"],
    purchaseorders: ["read"],
    salesorders: CRUD,
    rawmaterials: ["read"],
    finances: ["read"],
    users: ["read"],
    notifications: ["read", "create"],
  },
  finance: {
    products: ["read"],
    boms: ["read"],
    inventories: ["read"],
    purchaseorders: ["read", "update"],
    salesorders: ["read", "update"],
    rawmaterials: ["read"],
    finances: CRUD,
    users: ["read"],
    notifications: ["read", "create"],
  },
};

